posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

posts/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for
from models import Post, Tag
from .forms import PostForm
from app import db
from flask_security import login_required

posts = Blueprint('posts', __name__, template_folder='templates')



@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Сломался')
        return redirect(url_for('posts.index'))
    form = PostForm()
    return render_template('posts/create_post.html', form=form)


@posts.route('/<slug>/edit/', methods=['GET', 'POST'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()

    if request.form == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))
    form = PostForm(obj=post)
    return render_template('posts/edit.html', post=post, form=form)


@posts.route('/')
def index():
    q = request.args.get('q')
    page = request.args.get('page')
    if page and page.isidentifier():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q)|Post.body.contains(q)).all()
    else:
         posts = Post.query.order_by(Post.created.desc())

    pages = posts.paginate(page=page, per_page=10)
    return render_template('posts/index.html', posts=posts, pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    tags = post.tags
    return render_template('posts/post_detail.html', tags=tags, post=post,)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<form action="{{url_for('posts.create_post')}}" method="POST">
    {% for f in form %}
        <div class="form-group">
            {{f.label(class='control-label')}}
            {{f(class='form-control')}}
        </div>
    {% endfor %}
        <button type="submit" class="btn btn-success">Отправить</button>
</form>
    </div>
{% endblock %}

posts/templates/posts/edit.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<form action="{{url_for('posts.edit_post', slug=post.slug)}}" method="POST">
    {% for f in form %}
        <div class="form-group">
            {{f.label(class='control-label')}}
            {{f(class='form-control')}}
        </div>
    {% endfor %}
        <button type="submit" class="btn btn-success">Изменить</button>
</form>
    </div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Posts</h1>
{% for post in pages.items %}

<a href="{{url_for('posts.post_detail' ,slug=post.slug)}}">
  {{post.title}}
</a>
    {{post.body}}
{% endfor %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#"><</a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">></a></li>
  </ul>
</nav>
{% endblock content %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Posts</h1>

    {{post.title}}
        {% for tag in tags %}
      <button type="button" class="btn btn-warning"><a href="{{url_for('posts.tag_detail', slug=tag.slug)}}">{{tag.name}}</a></button>
        {% endfor %}

{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Posts</h1>

<h1>Posts for "{{tag.name}}" tag: </h1>


{% for post in posts %}

  <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{post.title}}</a>
{% endfor %}

{% endblock %}